GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJpa2hzYW4iLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjY1MjQ4MjQxLCJleHAiOjE2NjUzMzQ2NDF9.cQmHmVY-Qc3jnLK9G7JTdEtwhzA6uWh0BbsswVar9vI
###

GET http://localhost:8000/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJpa2hzYW4iLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjY1MjQ4MjQxLCJleHAiOjE2NjUzMzQ2NDF9.cQmHmVY-Qc3jnLK9G7JTdEtwhzA6uWh0BbsswVar9vI
###

POST  http://localhost:8000/users 
Content-Type: application/json

{
    "name" : "ikhsan2",
    "email" : "test@gmail.com",
    "password" : "123456",
    "confPassword" : "123456"
}

###

POST  http://localhost:8000/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "123456"
}


